name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  send_discord_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Discord Message
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_CREATED_AT: ${{ github.event.release.created_at }}
        run: |
          PAYLOAD=$(cat <<EOF
          {
            "content": null,
            "embeds": [
              {
                "title": "${RELEASE_NAME}",
                "url": "${RELEASE_URL}",
                "color": 8435015,
                "footer": {
                  "text": "Released"
                },
                "timestamp": "${RELEASE_CREATED_AT}",
                "image": {
                  "url" : "https://camo.githubusercontent.com/57f538cdf7ad2c4cc2bd44e42a95b34270fb1c3c8df0382e7920fd4449c099bb/68747470733a2f2f677265676f7279616d2e636f6d2f6173736574732f696d672f72657374727563747572652d696d6167652e77656270"
                }
              }
            ],
            "attachments": []
          }
          EOF
          )
          
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$DISCORD_WEBHOOK_URL"
